# Numpy Basics:

#### What is an Array ?

An Array is a data structure that store values of the same data type. In python this is the main difference between arrays and lists. While python losts can contain values correspondig to different data types, arrays in python can only contain values corresponding to same data type. 

In [1]:
import numpy as np  #importing Numpy library 

In [2]:
my_lst = [1,2,3,4,5,6,6,7,8] #list

arr = np.array(my_lst) #list to numpy array

In [3]:
type(arr) #to check data type

numpy.ndarray

In [4]:
arr  

array([1, 2, 3, 4, 5, 6, 6, 7, 8])

In [5]:
arr.shape #to get rows and columns of array (rows,columns)

(9,)

In [6]:
arr.reshape(3,3) #reshape(rows,columns)

array([[1, 2, 3],
       [4, 5, 6],
       [6, 7, 8]])

### Indexing

In [9]:
#accesing the array element

arr = np.array([1,2,3,4,5,6,7,8,9])

In [11]:
arr[3] #getting 4th element of array

4

In [15]:
arr = np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])

In [17]:
arr[0: ,:] #getting all the array elements

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
arr[1:,:2]

array([[4, 5],
       [7, 8]])

In [21]:
arr = np.arange(0,10) #creating an array (start,stop,step)

In [22]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
arr = np.arange(0,100,25) #here 0 - start value, 100 - stop value and 25- step value

In [24]:
arr

array([ 0, 25, 50, 75])

In [25]:
np.linspace(1,5,20) #linspace is similar to arange but it equally divides the values. (start,stop,point required)

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

In [28]:
#copy function and broadcasting

arr[2:] = 100  #replacing 2nd number onwards with value 100

In [29]:
arr

array([  0,  25, 100, 100])

In [30]:
arr[2:] = 10000

In [31]:
arr

array([    0,    25, 10000, 10000])

In [32]:
# to prevent this from happening we use .copy() function

arr1 = arr.copy() #creates a replica of arr

In [33]:
arr1

array([    0,    25, 10000, 10000])

In [34]:
# some condition useful in EDA

val = 2
arr<2 #returns True or False

array([ True, False, False, False])

In [35]:
arr[arr<100] #returns values less than 100

array([ 0, 25])

In [36]:
np.ones(5) #creates array with one

array([1., 1., 1., 1., 1.])

In [37]:
np.ones(10,dtype=int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [38]:
np.random.rand(3,3) #gives a random sample to form uniform distribution

array([[0.22397859, 0.42299356, 0.3869608 ],
       [0.27728529, 0.33324016, 0.52600321],
       [0.07070726, 0.03229364, 0.99090923]])

In [40]:
np.random.randn(2,2) #gives a random sample to form standard normal distribution

array([[-1.90016916, -0.17440385],
       [-0.17488985, -0.04229408]])

In [41]:
np.random.randint(0,100,20) #gives random number between(0,100,20 numbers)

array([92,  2, 83,  9, 48, 33, 12, 72, 49, 15, 84, 54, 65, 57, 18, 91, 79,
       49, 98, 72])