### NUMPY

Numpy is general purpose array processing package.It provides a high performance multidimensional array object and tools for wroking with these arrays.

In [1]:
import numpy as np

In [2]:
lst=[1,2,3,4,5,6,7,8]
arr=np.array(lst)

In [3]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [5]:
arr.size

8

In [6]:
arr.shape

(8,)

In [13]:
arr=arr.reshape(2,4)  #rows and columns

In [17]:
arr.shape

(2, 4)

In [25]:
print(arr)

[[1 2 3 4]
 [5 6 7 8]]


Indexing

In [18]:
arr[0]

array([1, 2, 3, 4])

In [19]:
arr[0][1]

2

In [20]:
arr[1][2]

7

In [21]:
arr[0][1:]

array([2, 3, 4])

In [32]:
arr[0:,0:2]

array([[1, 2],
       [5, 6]])

In [36]:
new_arr=np.arange(0,100,step=5)

In [37]:
new_arr

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

In [49]:
new_2=np.linspace(1,10,8)

In [50]:
new_2

array([ 1.        ,  2.28571429,  3.57142857,  4.85714286,  6.14285714,
        7.42857143,  8.71428571, 10.        ])

In [51]:
new_2.reshape(2,4)

array([[ 1.        ,  2.28571429,  3.57142857,  4.85714286],
       [ 6.14285714,  7.42857143,  8.71428571, 10.        ]])

In [54]:
arr[arr<5]

array([1, 2, 3, 4])

In [55]:
np.ones(4)

array([1., 1., 1., 1.])

In [57]:
np_uniform=np.random.rand(3,3)

In [58]:
np_uniform

array([[0.60003028, 0.35001469, 0.75584763],
       [0.42249661, 0.87347257, 0.43532385],
       [0.28444012, 0.88034073, 0.25406351]])

In [61]:
np_sta_norm=np.random.randn(4,4)

In [62]:
np_sta_norm

array([[ 1.69032532,  0.40989103, -0.28551488, -0.87187247],
       [ 0.41636855,  0.51310503,  1.56327796,  0.73762155],
       [-2.33940849,  2.09476081, -1.49634273, -1.01826351],
       [-0.26088288,  0.14025256, -2.37296815, -1.83939411]])

In [63]:
np_int=np.random.randint(0,100,8)

In [64]:
np_int

array([ 2, 17, 64, 78, 94, 47,  1, 17])

In [66]:
np.random.random_sample((2,2))

array([[0.21159429, 0.35222476],
       [0.20666906, 0.12017361]])

In [ ]:
|